/aruco_node:
  ros__parameters:
    marker_size: 0.150
    aruco_dictionary_id: DICT_4X4_50
    image_topic: /zed/zed_node/rgb_gray/image_rect_gray
    camera_info_topic: /zed/zed_node/rgb_gray/camera_info
    allowed_marker_ids:
      - "0"
      - "1"
      - "2"
      - "3"